spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: knberg
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: update
    main:
        allow-circular-references: true